### PR TITLE
Update cargo dependency from 0.24 to 0.37

### PR DESCRIPTION
**Pull request by david-mcgillicuddy-moixa**
We had some issues on crates using newer cargo features. We're successfully using the updated version internally.

The only non-mechanical parts are:
- add `docopt` as a dependency since `cargo` removed it from itself
- add `failure` as a dependency to interact with `cargo`'s various `Result` types

### CODE REVIEW

**Comment by markubiak** [comment]
Resolves my issues with generating a bb file for "librespot". I no longer get the following error:

> error: no matching package named `getrandom_package` found (required by `rand`)

**Comment by cardoe** [comment]
Looks like that error is related to the Rust version. This branch is a bit out of date so I cannot merge it whole sale but if you happen to rebase it I can if you also update the minimum version of Rust.

**Comment by david-mcgillicuddy-moixa** [comment]
Okay @cardoe it's rebased now. I apologise for the diff noise, it appears I ran cargo-fmt on it at some point without thinking about it.

**Comment by david-mcgillicuddy-moixa** [comment]
The build for 1.17.0 has failed, but I think that makes sense because we're specifically using a version of cargo that only supports newer features? I suppose if this was critical we could investigation partial compilation but personally I would bump the required minimum rust version that cargo-bitbake supports.

**Comment by david-mcgillicuddy-moixa** [comment]
@cardoe okay passes now - new MSRV is 1.34.0

**Pull request merged**
