### PR TITLE
Update to Cargo 0.41

### LINKED ISSUE #13: error: Invalid serialized PackageId for key `package.dependencies`
I'm getting the following error:

```
error: failed to parse lock file at: Cargo.lock

Caused by:
  invalid serialized PackageId for key `package.dependencies`
```

Probably this is caused by https://github.com/rust-lang/cargo/pull/7579 (I found this reference in https://github.com/sfackler/cargo-tree/issues/80, where the same issue was reported).

### PR DESCRIPTION
**Pull request by tylerwhall**
Needed for compatibility with the new Cargo.lock format.

Fixes #13

### CODE REVIEW

**Comment by cardoe** [comment]
@tylerwhall Can you bump the minimum Rust version (or even remove it) from https://github.com/cardoe/cargo-bitbake/blob/4693257eae41defd3d33aaf6602e2f6796d704fa/.travis.yml#L8 to something that works as part of this commit? If so then I'll merge this and put out a new release.

**Comment by tylerwhall** [comment]
I force pushed. Don't know why the check didn't run.

**Comment by cardoe** [comment]
Would you want me to move this to the meta-rust org btw?

**Comment by tylerwhall** [comment]
> Would you want me to move this to the meta-rust org btw?

Yeah, seems like that makes sense.

**Pull request merged**
